[server]
headless = true
address = "0.0.0.0"
port = 5001

[theme]
primaryColor = "#595bf5ff"
backgroundColor = "#383c44ff"
secondaryBackgroundColor = "#0c0d0fff"
textColor = "#e2e8f0"
font = "sans serif"
